language: node_js
node_js:
- '11'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: ci@radon.app
  api_key:
    secure: PiT+hKhR6bNkqULgOezheuYOB6qgrMbOjk5YU/YTj6SugTr4FntY934a4OujKvf7gvRsrLYJulVgX4OVRj7XTqAzHIcU3MKUO6kpMk7PdkhlN9+e0VpcK6HpAJz+f5+rzoof9CWien6zeb+iB3PH/BxxFNt2dJ6xk3tzvTjhHald1CSQ8qBJfBohHIyC4UvF9/GzL78+Q0/OxbD9akQOcBs0frLpp1NGiEiCeSQfTbqiMrbzLUQo3ArtDaW7qNjRhN0JkJAxTIfiq2Yey9xjcfUKILu44VvMLUghu7aAOmAPADNrKhayAo+mIkkdJTMdMVqLcVK+4q6jSuGAUOsMl01vNsQpSLN9780XliQNNEEkj26S6LfsWuA2if3o95hdSbun1U1fssy6aG/frE3li+gw3xICgkA3lbcm2USpQLSuPUhj+GShHii1CKvLDLtSG/iGtE7rcWKQJCW8uBEyQivirzKLn/tOQEk/bkvzk3OWqvAJmJfIPOb1oxjhhzJTl0xZ69z9+1A49gL/MWXOPgOKba641nfkVMm7fxuqMZ6to1aK5ptWTjmtyj2byc55DxAtr1Ec6kyabQeSU4uHcHbsPP0mB1rPC65jCZCaEgRtuvoGBrpX8LC82Hs6kMQumezrXyc6LS7aw/GZ6BFVIZXdDEbDirWgiF6qiEmT7VU=
  on:
    tags: true
    repo: RadonApp/radon-extension-plugin-listenbrainz
