language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g NeApp/neon-extension-build#$TRAVIS_BRANCH || npm install -g NeApp/neon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: neapp-ci@me.dgardiner.net
  api_key:
    secure: D6RbWw4tEzu/K/KkTVsJ/mwnMYQuWgh4Q+SNXiw+YAkCO0bWMYevcWCpXqtVruPavU7dilaOYkb9CKqnbnolD72I/VjiRgTcbUs0QH8BWXL73yYfH5Wa60InfIDVuMhxRQQ0Poy0hidpEaeO+HOl9lMMiQYUHpvFkMvgnUlK1sN7DEPIKAlv8cVcscap0NcRANlKpRRZuVZZsaySfjJjQFwRc+69QbnXZfNNHS24WuE/dl6TjNvNQiz74H3MmLHDeOue4JkLJjjzxjCXeqdOuUvQkNAzwPOTYYGBZivs4/TOOKV8pyx2xOIdeQFXgxw6uTtUkQJDXeyz1wym72kwKQlGXHNeLqwcspXXW86XZlX8mrzZDI2TK1jy8fYLKMzbiS7dRpo+tHy3S7Gbs6xLMAzmSu4xl2LOxg/dMhFKkWCWKHFrSpTqRo18rfqTsHMOYIm4D4otAaatggidXRrgLEFFbcgAW6RyNTEpbIIxToOR4bgOBwowthpxRNA8H+NnyPcbnNepXL91tBKHaPfPjF0JvTMp3L5Cg7hKV63us6+3RzNJ3HknQjo2+AKqdba4oIrAqWt9gySXGuhQy/rgUjd5uasOlRvNqzWexZkTNTp6pbBANL8ukL6EuZb2WwmsNaa+HHhIt8g07R6lEJULdLdj0dqpJvbgOpe4Xwr8aGQ=
  on:
    repo: NeApp/neon-extension-destination-listenbrainz
    tags: true
